name: rag-langgraph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - langchain-community
      - langchain-core
      - langchain-text-splitters
      - langchain-huggingface
      - sentence-transformers
      - faiss-cpu
      - pypdf
      - langgraph

